const types = {
    GET_LOCATION: 'GET_LOCATION', 
    
    GET_WEATHER: 'GET_WEATHER',
    GET_WEATHER_SUCCESS: 'GET_WEATHER_SUCCESS',
    GET_WEATHER_FAILED: 'GET_WEATHER_FAILED',

    GET_AREA: 'GET_AREA',
    GET_AREA_SUCCESS: 'GET_AREA_SUCCESS',
    GET_AREA_FAILED: 'GET_AREA_FAILED',

    CHANGE_TEMP_TYPE: 'CHANGE_TEMP_TYPE',
    SET_ERROR: 'SET_ERROR'
}

export default types